name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *" # هر روز ساعت ۰۰:۰۰ UTC اجرا شود
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: silverboy66000
          outputs: |
            ./dist/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
